### ISSUE TITLE
Major Bug - Always overrides native CustomEvent across all browsers

### ISSUE THREAD

**Issue by andrejpavlovic** [krambuhl/custom-event-polyfill#12]
The polyfill test always fails and as a result the browser never uses the native implementation even when it is available. 

The issue is with this code:
https://github.com/krambuhl/custom-event-polyfill/blob/71749f01e4e8e3e7e52ffb646bb50c4f78f87961/custom-event-polyfill.js#L7-L15

Instead of
```javascript
var ce = new window.CustomEvent('test'); 
```
is should be
```javascript
var ce = new window.CustomEvent('test', {cancelable: true});
```
otherwise `ce.defaultPrevented` always equals to `false` and the error is always thrown.

**Comment by jbreckmckye** [comment]
@andrejpavlovic Could you write that up as a PR?

**Comment by davidpelayo** [comment]
@jbreckmckye when are we merging #13 so this gets closed?

**Comment by jbreckmckye** [comment]
@davidpelayo I don't know. When ARE we? I'm not a project admin.

**Comment by davidpelayo** [comment]
Fair enough 😆 
@krambuhl, when #13 gets merged?

**Comment by kumarharsh** [comment]
In the meanwhile, you can use this fork which has @andrejpavlovic and @shrpne's changes
https://www.npmjs.com/package/@playlyfe/custom-event-polyfill

**Comment by krambuhl** [comment]
PR has been merged, closing this ticket.
