### ISSUE TITLE
AppVeyor integration

### ISSUE THREAD

**Issue by limonte** [krambuhl/custom-event-polyfill#15]
From https://engineering.videoblocks.com/these-four-clean-code-tips-will-dramatically-improve-your-engineering-teams-productivity-b5bd121dd150

> “If it isn’t tested, it’s broken”

There are tests, but you're not running them anywhere and users can't be sure that the polyfill tests are passing. AppVeyor is the default solution for IE tests.

**Comment by kumarharsh** [comment]
@limonte I've added the tests in my fork - they'll be added here soon.

**Comment by limonte** [comment]
Great! I will reopen this issue then, I thought it was ignored :)

**Comment by kumarharsh** [comment]
Completed the integration and published to https://npmjs.com/package/custom-event-polyfill
