### ISSUE TITLE
Looking for an owner

### ISSUE THREAD

**Issue by krambuhl** [krambuhl/custom-event-polyfill#16]
If you are interested in taking ownership of this github repo and the NPM module, please respond in this thread.

@kumarharsh you already have a good thing (https://github.com/kumarharsh/custom-event-polyfill), are you interested?

**Comment by kumarharsh** [comment]
Sure.

**Comment by kumarharsh** [comment]
@krambuhl I've setup tests on saucelabs too for my fork of the project. Can I merge that in here?

**Comment by davidpelayo** [comment]
I'm up to be a collaborator, if you guys want or consider it's useful. Thanks!

**Comment by krambuhl** [comment]
@kumarharsh I'm adding you as a collaborator on this repo and `kumarharsh` on npm as an additional maintainer.    

Feel free to PR your changes into this repo, version bump, and publish to npm.  I've never changed ownership of a open source project before, please let me know if there is anything else I can do.

**Comment by kumarharsh** [comment]
Thanks @krambuhl. I'll make the changes soon.

**Comment by kumarharsh** [comment]
I think a simpler way would be that you give me permission to publish to your repo on npm.

**Comment by kumarharsh** [comment]
So after giving the issue some thought, it seems like it'll be too much administrative overhead to setup all those CI systems, etc. And on top of that, you will need to keep changing authentication tokens, etc when they are invalidated (like npm did recently) or Github token changes, or Saucelabs introduce some changes, etc in the future. Plus if things go wrong, I'll have to prod you to login to the saucelabs account to see if connections are happening properly, or edit travis config, etc. I think it might become more pain than it'd be worth for you (and me).

So, I published a new npm `custom-event-polyfill` version 1.0.6 (thanks for making me admin) - but had to do it from my fork. I hope that's OK with you.
