### ISSUE TITLE
I'm having problems with SSR 'window is not defined'

### ISSUE THREAD

**Issue by caiocaprio** [krambuhl/custom-event-polyfill#18]
`CustomEvent.prototype = window.Event.prototype;` in  custom-event-polyfill\custom-event-polyfill.js:42
                          
> ReferenceError: window is not defined

**Comment by justinhp** [comment]
@caiocaprio yes, that's bc node doesn't have a concept of window....you have to "polyfill" window with jsdom or something or only execute this polyfill client side

**Comment by kumarharsh** [comment]
This has been fixed in later here: https://github.com/kumarharsh/custom-event-polyfill

You will need to follow @justinhp's advice for using it server-side.
