### ISSUE TITLE
Add "Usage" section

### ISSUE THREAD

**Issue by halt-hammerzeit** [krambuhl/custom-event-polyfill#7]
First, it's not "Useage".
Second, how should one use it?
I suppose something like this (should be in the readme):
```js
require('custom-event-polyfill')
// or
import CustomEvent from 'custom-event-polyfill'
```

**Comment by halt-hammerzeit** [comment]
And you should probably add `return CustomEvent` in the end.

**Comment by krambuhl** [comment]
These are good additions, seems like you could make the PR instead of nitpicking my spelling skills 😄

**Comment by halt-hammerzeit** [comment]
See the PR
